### ISSUE TITLE
compatible with redmin 2.3.2?

### ISSUE THREAD

**Issue by cforce** [evolvingweb/redmine_easy_edit#2]

**Comment by fengyedou** [comment]
yes, nothing happens on redmine 2.3.2, by the way, is there any good plug-in for more nice display for redmine wiki, e.g. redmine default table function in wiki is not good, it can not easily to draw cell color for a table.

**Comment by dergachev** [comment]
As of last week the plugin works for us in Redmine 2.5
Hopefully 2.3 is similar.

See https://github.com/evolvingweb/redmine_easy_edit/commits/master
